### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by mundschenk-at** [sherrillmix/wp_monsterid#1]
I'd like to re-use `wp_monsterid` in https://github.com/mundschenk-at/avatar-privacy (as a replacement for Gravatar's `monsterid` default images). However, I've not found any explicit license information for `wp_monsterid`. Theoretically, everything in the WP.org repository should be GPLv2 (or `GPL-2.0-or-later`), but @splitbrain has the [original algorithm/artwork licensed as `CC BY 2.5`](https://www.splitbrain.org/projects/monsterid) and since `wp_monsterid` stems from the early days of WordPress, it might be grandfathered in.

As far as I know, `CC BY 2.5` code could not be used in a GPL-licensed project, but you might either have received a separate license grant from @splitbrain or re-implemented the concept without actually using his code, allowing for GPL licensing?

**Comment by splitbrain** [comment]
FYI my original code is now available under MIT and the link back requirement was removed, so there are no compatibility issues with GPL anymore.

See https://github.com/splitbrain/monsterID

**Comment by mundschenk-at** [comment]
Hi @sherrillmix! A quick verification of the license would be great (GPL preferred by me, MIT fine as well of course), to put this issue to rest.

**Comment by sherrillmix** [comment]
I'm sorry I don't think this showed up in my notifications for the original issue submission. Weird.

It's been quite a while but I believe I largely/entirely reimplemented the code. However I had seen the code from @splitbrain so I'm not sure where things would fall legally. Fortunately it doesn't seem to matter based on the licensing clarification from splitbrain.

I've updated the readme to list GPL v2+.

**Comment by mundschenk-at** [comment]
Thank you. I've also talked with Katherine Garner (Lemm) and she is fine with GPL v2+ for her donated monster parts as well.

**Comment by sherrillmix** [comment]
Thanks @mundschenk-at. Good luck with your plugin.
